
install.packages("languageserver")
install.packages("IRkernel")
install.packages("data.table")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("knitr")
install.packages("magrittr")
install.packages("curl")
install.packages("ISLR")
IRkernel::installspec()